[package]
name = "climb"
version = "1.0.1"
edition = "2021"
description = "Library for creating simple command-line interfaces"
readme = "README.md"
repository = "https://github.com/hunterlawson/climb"
license = "MIT OR Apache-2.0"
keywords = ["command", "line", "interface", "cli", "application"]
categories = ["command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"