[package]
name = "climb"
version = "0.1.0"
edition = "2021"
description = "Library for creating simple command-line interfaces"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
